{% set version = "2.2.27.15" %}

package:
  name: udunits2
  version: {{ version }}

source:
  url: https://github.com/Unidata/UDUNITS-2/archive/v{{ version }}.tar.gz
  sha256: 4b9b55312c4cc43460c3d747655d188178940facc87083351dd3c4dad98ead29

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - texinfo  # [not win]
  host:
    - expat
  run:
    - expat

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: UCAR OSI approved
  license_file: COPYRIGHT
  summary: The UDUNITS package supports units of physical quantities.

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - dkillick
