{% set version = "2.2.27.6" %}

package:
  name: udunits2
  version: {{ version }}

source:
  url: https://github.com/Unidata/UDUNITS-2/archive/v{{ version }}.tar.gz
  sha256: 74fd7fb3764ce2821870fa93e66671b7069a0c971513bf1904c6b053a4a55ed1

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - texinfo  # [not win]
  host:
    - expat
  run:
    - expat

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: UCAR OSI approved
  license_file: COPYRIGHT
  summary: 'The UDUNITS package supports units of physical quantities.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - dkillick
