{% set version = "2.2.28" %}

package:
  name: udunits2
  version: {{ version }}

source:
  url: https://artifacts.unidata.ucar.edu/repository/downloads-udunits/{{ version }}/udunits-{{ version }}.tar.gz  # [not win]
  sha256: 590baec83161a3fd62c00efa66f6113cec8a7c461e3f61a5182167e0cc5d579e  # [not win]
  url: https://artifacts.unidata.ucar.edu/repository/downloads-udunits/{{ version }}/udunits-{{ version }}.zip  # [win]
  sha256: e09d31db68f9a840a0663c7e9909101957733ff0310761b9906f4722e0d92c44  # [win]

build:
  number: 1
  detect_binary_files_with_prefix: true
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [not win]
    - autoconf  # [not win]
    - automake  # [not win]
    - libtool  # [not win]
    - texinfo  # [not win]
  host:
    - expat
  run:
    - expat

test:
  commands:
    - udunits2 -h
    - udunits2 -H meter -W miles

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  license: LicenseRef-BSD-UCAR
  license_file: COPYRIGHT
  summary: 'The UDUNITS package supports units of physical quantities.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - pelson
    - DPeterK
    - zklaus
    - xylar
