appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: M7LMIHPXjcOoOcdsrg821VO6PeIwWqy7dfH9pgkYpIqAWcISZQyS+xCzFpYClycLxr6GjSROYInohNbHtRBKjOyufIcP/4nIo8gOip8zT6bT89xDLy3X5hTxwf7no8LDeABmuyY0ZXyztF+2WPXQFf0Qm30O325hkB/reYukFfoka+AL4YSkX6fFIhp4K/3Mc5k/ahUSN/YSZxR5fvPahTRrOLGQfSynBmAQAWvy6BBUBbBNuSqH2C3I8IRxzXt4MUTkpobst/6TXfJvsxWxH5qTlngRCh9rirI2eqmiUhEpuXpHVmFSdZbZrpW5yH14CTJVwRL/IveI1cH7rl8Xcqb8qiqwLZmNqMXiXw4yDxgLpJTMqNeZwo7rqk0uLMGzLMh4Vn/fbKgWfLj0Xsy6I5gHP2hEAc0j4sIRD7VT5zvWZxQLRpUN9JXzVX0AElhDX7LpFGW68ouhEsFRwN4P/m+bR6iwz+Pixxu4MVAe8biVXte/iDq3dGT334jPuPUUCby10UanRTuYygXcY7cyf8qimZjvzZ21PjHYa3GkE4XSDr+eS+lBceUV63RSyOkul4Db5aKgNxsprrXIGnJiMiVSJL6RG5DtK/RRyog4HGqdfP545vX1DUCCs/pXF0uC2KfxBNrlD7U5xE5RdlAA8MKw5tDWsE2je3Mym9Crwk0=}
