travis:
  secure:
    BINSTAR_TOKEN: jAbynvfDo9nphTKZ3cTecgD/09jEMvrQYQ2lFUkgrBEBCXvoArA/0X1FdbWw3nw9CHUGphAn6r6RHRZVxHkQ+id0eYdAA2ehGZIQqPMsSwOQoGoSQ82+A3J45gwm+LQu/MnOM9h4g5SK3CQvgJf9nBKPfXfQ7crpjyagLrS/yqzgrNLmBPBVUHLUvTluFDE1gtoTgU548aoTmazh6k9qPa+C1d1hjLjIz1r21i+kYSd/KrKSIP2ZuERbP7kZGSF7UTYZ3d7ikiSVtrNAyvnghEPFNKRxW4pkh8a56dXXBGmvrOd+HtFXkIcFC9gvXOH7A9OvOhsoSEF0MZMDCnQfojCl/TXSh4wSENtH6IQGRJuprvGygeKBaqPIm8MjYaouPF8j58mPP01CRScpVXz/cKW8PEHMS11I+bCMTixMmxMXTz5XRL1060b41A1SA3yitlGgCuPk+fYTF4iwe9qZzNrPsumcXBtOq2P0qQYgj9ldBdLuiUw7W7ERPewsE66cgogHd5PITVi0g8aBVKMt23XAGIHP6cKl+ogOdpTWBLSdqJrMIiAWf59ImV83/kjLPv9edBGielMhe2W91Wh2yCKbl2xxYs29l+4NeXH+yNNajUJ9G+gvqh8AAkVtYIyYSTvIXZQ904Q7Vod73xDvrAkSjZdqMkOEYoPfzmk8Mr4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
